### PR TITLE
DynamoDB Leader Monitor: On Next Should Always Provide MasterDescription

### PR DESCRIPTION
**Pull request by crioux-stripe**
This is an extension of @kmg-stripe 's fix in https://github.com/Netflix/mantis/pull/691 that is ready to merge.

### Context

The DynamoDBMasterMonitor had cases where it may propagate a `null` value when `getLatestMaster()` is called, despite having some protections against it. I've removed the `AtomicReference` to the latest and just rely on the `BehaviorSubject` to return the latest value.

### Checklist

- [x] `./gradlew build` compiles code correctly
- [x] Added new tests where applicable
- [x] `./gradlew test` passes all tests
- [x] Extended README or added javadocs where applicable

### CODE REVIEW

**Review by Andyz26 — APPROVED** [review]

**Comment by crioux-stripe** [comment]
I don't have tag pushing rights, but if someone could tag this `v3.1.1-rc.1` that would be awesome!

**Comment by Andyz26** [comment]
> I don't have tag pushing rights, but if someone could tag this `v3.1.1-rc.1` that would be awesome!

@crioux-stripe I think @kmg-stripe was able to push the RC tag, and you have the same role in settings. Can you try pushing the tag and let me know if you get any errors?

**Comment by crioux-stripe** [comment]
@Andyz26 I did think it was kind of odd but I'm getting:

```
crioux@st-crioux1 mantis % git push origin tag v3.1.1-rc.1
ERROR: Permission to netflix/mantis.git denied to crioux-stripe.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
crioux@st-crioux1 mantis % cat .git/config
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = git@github.com:netflix/mantis.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
```

**Comment by Andyz26** [comment]
@crioux-stripe, hmm, this is weird: "fatal: Could not read from remote repository." Maybe try reattaching the public SSH keys?
I just checked again, and there is no difference between your account setting and Kevin's. @sarahwada-stripe also got the same permission role. Does it work for you?

**Comment by crioux-stripe** [comment]
@Andyz26 

That did the trick. The default Stripe one appeared to be an older RSA key. I added a new `ed25519` key and everything appears to work:

```
crioux@st-crioux1 mantis % git push
Everything up-to-date
```

(This used to produce an error.)

**Pull request merged**
